# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1991176392224
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
Z = np.zeros((10,10))
print(Z.dtype)
print(Z.size)
print(Z.itemsize)
print(Z.size * Z.itemsize)

float64
100
8
800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
np.add?

Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\programs\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array w

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [22]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [34]:
Z = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])

np.where(Z)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

#### 11. Create a 3x3 identity matrix (★☆☆)

In [36]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [42]:
Z = np.random.random((3,3,3))
Z

array([[[0.4824577 , 0.5978092 , 0.72729673],
        [0.88736846, 0.70174719, 0.85787551],
        [0.33151392, 0.2474271 , 0.05489308]],

       [[0.33727308, 0.29565508, 0.6388008 ],
        [0.74233726, 0.97797789, 0.06080626],
        [0.49673961, 0.88826869, 0.8079628 ]],

       [[0.7877595 , 0.36631439, 0.31906588],
        [0.2644966 , 0.94420888, 0.45751535],
        [0.21797901, 0.20048553, 0.15912934]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [65]:
Z = np.random.randint(1,10,(10,10))
print(Z)
print(np.min(Z))
print(np.max(Z))

[[9 8 2 2 2 9 1 4 8 4]
 [9 4 7 2 2 2 3 1 9 9]
 [7 2 3 7 7 6 8 4 8 1]
 [6 8 2 2 2 5 2 2 7 4]
 [9 5 2 7 3 5 8 4 6 8]
 [8 6 6 1 2 4 6 9 3 6]
 [1 7 4 5 3 6 7 6 9 9]
 [9 3 4 1 3 6 8 2 5 1]
 [6 2 5 5 9 8 9 5 5 1]
 [9 1 1 1 8 8 1 4 9 2]]
1
9


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [161]:
Z = np.random.rand(30)
Z.mean()

0.5233300503042171

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [170]:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [185]:
Z = np.ones((10,10))
new_Z = np.pad(Z, 1, mode="constant")
new_Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [192]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [197]:
Z = np.diag((1,2,3,4), k=-1)
Z


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [207]:
Z = np.ones((8,8))
Z[::2,::2] = 0
Z[1::2,1::2] = 0
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [209]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [214]:
Z = np.array([[0,1],
              [1,0]])
Z_tile = np.tile(Z,(4,4))
Z_tile

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [220]:
Z = np.random.random((5,5))
print(Z)
Z_norm = (Z - Z.mean())/Z.std()
print(Z_norm)


[[0.33948739 0.49464685 0.31502709 0.54543909 0.68247808]
 [0.2203669  0.48533745 0.99298136 0.3241613  0.03536192]
 [0.81735173 0.50330678 0.05278386 0.89030503 0.40451438]
 [0.92927318 0.40207817 0.07683228 0.24530114 0.35026051]
 [0.75072829 0.18474815 0.43097365 0.87324542 0.53376109]]
[[-0.49524565  0.07084058 -0.58448701  0.2561518   0.75612703]
 [-0.92984675  0.03687603  1.88897214 -0.5511616  -1.60482187]
 [ 1.2482022   0.10243562 -1.5412594   1.51436618 -0.25800016]
 [ 1.65653822 -0.26688845 -1.45352073 -0.83887626 -0.45594086]
 [ 1.0051322  -1.05979876 -0.16146572  1.45212564  0.2135456 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [222]:
Z = np.dtype([("R",np.ubyte, 1),
              ("G",np.ubyte, 1),
              ("B",np.ubyte, 1),
              ("A",np.ubyte, 1),])
Z

C:\Users\馬淵 健\AppData\Local\Temp\ipykernel_14028\57767540.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.dtype([("R",np.ubyte, 1),


dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [226]:
a = np.ones((5,3))
b = np.ones((3,2))
print(a)
print(b)
Z = a.dot(b)
Z

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [247]:
Z = np.random.randint(0,10,(10))
print(Z)
Z[(Z >= 3) & (Z <= 8)] *= -1
Z

[8 5 6 5 4 1 9 6 2 1]


array([-8, -5, -6, -5, -4,  1,  9, -6,  2,  1])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5),-1))

print(sum(range(5),-1))

9
9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [16]:
Z = np.arange(7)
print(Z)
print(Z**Z)
print(2<<Z>>2)
print(Z <- Z)
print(1j * Z)
print(Z/1/1)
print(Z<Z>Z)

[0 1 2 3 4 5 6]
[    1     1     4    27   256  3125 46656]
[ 0  1  2  4  8 16 32]
[False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j]
[0. 1. 2. 3. 4. 5. 6.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
Z = np.array(0)
print(Z / Z)
print(Z // Z)
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\馬淵 健\AppData\Local\Temp\ipykernel_21328\1765865735.py:2: RuntimeWarning: invalid value encountered in divide
  print(Z / Z)
C:\Users\馬淵 健\AppData\Local\Temp\ipykernel_21328\1765865735.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(Z // Z)
C:\Users\馬淵 健\AppData\Local\Temp\ipykernel_21328\1765865735.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [40]:
Z = np.random.uniform(-10,10,10)
print(Z)
print((np.copysign(np.ceil(np.abs(Z)), Z)).astype(int))

[ 2.10713722  8.70873579  8.82348354  7.17056251 -3.31996792 -2.34949501
  4.61203405 -4.54244931 -5.19188151  9.68718923]
[ 3  9  9  8 -4 -3  5 -5 -6 10]


#### 30. How to find common values between two arrays? (★☆☆)

In [134]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a)
print(b)

np.intersect1d(a,b)

[0 7 0 2 5 7 8 9 3 1]
[5 8 0 1 1 5 2 3 3 1]


array([0, 1, 2, 3, 5, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [137]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [141]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\馬淵 健\AppData\Local\Temp\ipykernel_21328\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [154]:
Z = np.datetime64('today', 'D') - np.timedelta64(1,'D')
print(Z)
Z = np.datetime64('today', 'D')
print(Z)
Z = np.datetime64('today', 'D') + np.timedelta64(1,'D')
print(Z)

2026-05-08
2026-05-09
2026-05-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [4]:
Z = np.arange("2016-07","2016-08",dtype="datetime64[D]")
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,-2,out=A)
np.multiply(A,B,out=A)
A

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [40]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z // 1)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int).astype(float))
print(np.trunc(Z))

[5.55261002 1.76613359 4.07354989 4.43953522 2.85653071 8.13785732
 5.00298037 8.70342731 4.25556941 1.50710052]
[5. 1. 4. 4. 2. 8. 5. 8. 4. 1.]
[5. 1. 4. 4. 2. 8. 5. 8. 4. 1.]
[5. 1. 4. 4. 2. 8. 5. 8. 4. 1.]
[5. 1. 4. 4. 2. 8. 5. 8. 4. 1.]
[5. 1. 4. 4. 2. 8. 5. 8. 4. 1.]
[5. 1. 4. 4. 2. 8. 5. 8. 4. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.tile(range(5),(5,1))
Z

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [64]:
def hoge():
    for i in range(10):
        yield i

Z = np.fromiter(hoge(),dtype=int,count=-1)
print(Z)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [79]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [115]:
Z = np.random.random(10)
Z.sort()
Z

array([0.05920204, 0.30402578, 0.30789269, 0.43503275, 0.49398558,
       0.49519497, 0.52378841, 0.69338072, 0.69746432, 0.92020414])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [120]:
Z = np.arange(5)
%timeit np.add.reduce(Z)
%timeit Z.sum()
%timeit sum(Z)

1.48 µs ± 20.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.65 µs ± 2.06 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.1 µs ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [278]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
print(np.allclose(A,B))
print(np.array_equal(A,B))

[1 0 0 0 0]
[1 0 0 0 0]
True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [283]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
Z = np.column_stack([R,T])
print(Z)


[[0.26843946 0.30806548]
 [0.56564429 0.24871774]
 [0.54274209 0.95757056]
 [0.75485829 0.63044237]
 [0.26652476 0.56070129]
 [0.93490282 0.31184277]
 [0.00814365 0.89802044]
 [0.20558728 0.67986027]
 [0.12837324 0.42890321]
 [0.5604157  0.90004423]]
[[0.40861239 0.85402514]
 [0.61791098 0.41426135]
 [1.10068632 1.05515343]
 [0.98349816 0.69582698]
 [0.62082315 1.12706915]
 [0.98554005 0.32195126]
 [0.89805736 1.56172813]
 [0.71026482 1.27714247]
 [0.44770264 1.27997648]
 [1.06025722 1.01388616]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [286]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.19775366 0.82583818 0.6281001  0.94239409 0.01783884 0.30093224
 0.26111041 0.75175751 0.91358325 0.09552873]
[0.19775366 0.82583818 0.6281001  0.         0.01783884 0.30093224
 0.26111041 0.75175751 0.91358325 0.09552873]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)